
spring:
  h2:
    console:
      enabled: 'true'
      path: /telgatech-h2-ui
  datasource:
    username: telgatech
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: $telgatech123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update


server:
 port : 8082